/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utilisateur;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Yannick MVOGO BEKONO
 */
public class createP extends javax.swing.JFrame {

    /**
     * Creates new form createP
     */
    private profiles parent;
    private Profile profile;
    private int action;
    private boolean state(char c) {
        return c == '1';
    }
    private String state(boolean s) {
        if(s) return "1";
        else return "0";
    }
    private void initCheckBoxes(String privileges) {
        p1.setSelected(state(privileges.charAt(0)));
        p3.setSelected(state(privileges.charAt(2)));
        p4.setSelected(state(privileges.charAt(3)));
        p5.setSelected(state(privileges.charAt(4)));
        p6.setSelected(state(privileges.charAt(5)));
        p7.setSelected(state(privileges.charAt(6)));
        p8.setSelected(state(privileges.charAt(7)));
        p9.setSelected(state(privileges.charAt(8)));
        p10.setSelected(state(privileges.charAt(9)));
        p11.setSelected(state(privileges.charAt(10)));
        p12.setSelected(state(privileges.charAt(11)));
        p13.setSelected(state(privileges.charAt(12)));
        p14.setSelected(state(privileges.charAt(13)));
        p15.setSelected(state(privileges.charAt(14)));
        p16.setSelected(state(privileges.charAt(15)));
        p17.setSelected(state(privileges.charAt(16)));
        p18.setSelected(state(privileges.charAt(17)));
        p19.setSelected(state(privileges.charAt(18)));
        p20.setSelected(state(privileges.charAt(19)));
        p21.setSelected(state(privileges.charAt(20)));
        p22.setSelected(state(privileges.charAt(21)));
        p23.setSelected(state(privileges.charAt(22)));
        p24.setSelected(state(privileges.charAt(23)));
        p2.setSelected(state(privileges.charAt(1)));
    }
    
    public createP(profiles parent, int action, Profile p) {
        initComponents();
        this.action = action;
        this.parent = parent;
        if(action == 1) {
            //modifier
            profile = p;
            nom.setText(p.getNom());
            initCheckBoxes(Arrays.toString(p.getPrivileges()));
        }
        //creer
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        p1 = new javax.swing.JCheckBox();
        p2 = new javax.swing.JCheckBox();
        p3 = new javax.swing.JCheckBox();
        p4 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        p5 = new javax.swing.JCheckBox();
        p6 = new javax.swing.JCheckBox();
        p7 = new javax.swing.JCheckBox();
        p8 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        p9 = new javax.swing.JCheckBox();
        p10 = new javax.swing.JCheckBox();
        p11 = new javax.swing.JCheckBox();
        p12 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        p13 = new javax.swing.JCheckBox();
        p14 = new javax.swing.JCheckBox();
        p15 = new javax.swing.JCheckBox();
        p16 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        p17 = new javax.swing.JCheckBox();
        p18 = new javax.swing.JCheckBox();
        p19 = new javax.swing.JCheckBox();
        p20 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        p21 = new javax.swing.JCheckBox();
        p22 = new javax.swing.JCheckBox();
        p23 = new javax.swing.JCheckBox();
        p24 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Privileges", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Donnees des etudiants"));

        p1.setText("Afficher");

        p2.setText("Creer");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        p3.setText("Modifier");

        p4.setText("Supprimer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p1)
                .addGap(18, 18, 18)
                .addComponent(p2)
                .addGap(18, 18, 18)
                .addComponent(p3)
                .addGap(18, 18, 18)
                .addComponent(p4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p1)
                .addComponent(p2)
                .addComponent(p3)
                .addComponent(p4))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Donnees des enseignants"));

        p5.setText("Afficher");

        p6.setText("Creer");
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });

        p7.setText("Modifier");

        p8.setText("Supprimer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p5)
                .addGap(18, 18, 18)
                .addComponent(p6)
                .addGap(18, 18, 18)
                .addComponent(p7)
                .addGap(18, 18, 18)
                .addComponent(p8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p5)
                .addComponent(p6)
                .addComponent(p7)
                .addComponent(p8))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Donnees des matieres"));

        p9.setText("Afficher");

        p10.setText("Creer");
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10ActionPerformed(evt);
            }
        });

        p11.setText("Modifier");

        p12.setText("Supprimer");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p9)
                .addGap(18, 18, 18)
                .addComponent(p10)
                .addGap(18, 18, 18)
                .addComponent(p11)
                .addGap(18, 18, 18)
                .addComponent(p12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p9)
                .addComponent(p10)
                .addComponent(p11)
                .addComponent(p12))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Notes des etudiants"));

        p13.setText("Afficher");

        p14.setText("Creer");
        p14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p14ActionPerformed(evt);
            }
        });

        p15.setText("Modifier");

        p16.setText("Supprimer");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p13)
                .addGap(18, 18, 18)
                .addComponent(p14)
                .addGap(18, 18, 18)
                .addComponent(p15)
                .addGap(18, 18, 18)
                .addComponent(p16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p13)
                .addComponent(p14)
                .addComponent(p15)
                .addComponent(p16))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Utilisateurs"));

        p17.setText("Afficher");

        p18.setText("Creer");
        p18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p18ActionPerformed(evt);
            }
        });

        p19.setText("Modifier");

        p20.setText("Supprimer");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p17)
                .addGap(18, 18, 18)
                .addComponent(p18)
                .addGap(18, 18, 18)
                .addComponent(p19)
                .addGap(18, 18, 18)
                .addComponent(p20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p17)
                .addComponent(p18)
                .addComponent(p19)
                .addComponent(p20))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Profiles"));

        p21.setText("Afficher");

        p22.setText("Creer");
        p22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p22ActionPerformed(evt);
            }
        });

        p23.setText("Modifier");

        p24.setText("Supprimer");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p21)
                .addGap(18, 18, 18)
                .addComponent(p22)
                .addGap(18, 18, 18)
                .addComponent(p23)
                .addGap(18, 18, 18)
                .addComponent(p24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p21)
                .addComponent(p22)
                .addComponent(p23)
                .addComponent(p24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Nom du profile");

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6ActionPerformed

    private void p10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p10ActionPerformed

    private void p14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p14ActionPerformed

    private void p18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p18ActionPerformed

    private void p22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p22ActionPerformed
    private String parseCheckBoxes(){
        String s = "";
        s = s.concat(state(p1.isSelected()));
        s = s.concat(state(p2.isSelected()));
        s = s.concat(state(p3.isSelected()));
        s = s.concat(state(p4.isSelected()));
        s = s.concat(state(p5.isSelected()));
        s = s.concat(state(p6.isSelected()));
        s = s.concat(state(p7.isSelected()));
        s = s.concat(state(p8.isSelected()));
        s = s.concat(state(p9.isSelected()));
        s = s.concat(state(p10.isSelected()));
        s = s.concat(state(p11.isSelected()));
        s = s.concat(state(p12.isSelected()));
        s = s.concat(state(p13.isSelected()));
        s = s.concat(state(p14.isSelected()));
        s = s.concat(state(p15.isSelected()));
        s = s.concat(state(p16.isSelected()));
        s = s.concat(state(p17.isSelected()));
        s = s.concat(state(p18.isSelected()));
        s = s.concat(state(p19.isSelected()));
        s = s.concat(state(p20.isSelected()));
        s = s.concat(state(p21.isSelected()));
        s = s.concat(state(p22.isSelected()));
        s = s.concat(state(p23.isSelected()));
        s = s.concat(state(p24.isSelected()));
        return s;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(nom.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Saisissez le nom du nouveau profile", "Nom non valide", JOptionPane.ERROR_MESSAGE);
        }
        else {
            if(action == 1) {
                //modifier
                profile.setNom(nom.getText());
                profile.setPrivileges(parseCheckBoxes());
                profile.update();
            }
            else if(action == 2){
                //creer
                profile = new Profile(nom.getText(), parseCheckBoxes());
                if(profile.create()){
                    JOptionPane.showMessageDialog(this, "Le nouveau profile a bien ete enregistre", "Profile enregistre", JOptionPane.INFORMATION_MESSAGE);
                }
                parent.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nom;
    private javax.swing.JCheckBox p1;
    private javax.swing.JCheckBox p10;
    private javax.swing.JCheckBox p11;
    private javax.swing.JCheckBox p12;
    private javax.swing.JCheckBox p13;
    private javax.swing.JCheckBox p14;
    private javax.swing.JCheckBox p15;
    private javax.swing.JCheckBox p16;
    private javax.swing.JCheckBox p17;
    private javax.swing.JCheckBox p18;
    private javax.swing.JCheckBox p19;
    private javax.swing.JCheckBox p2;
    private javax.swing.JCheckBox p20;
    private javax.swing.JCheckBox p21;
    private javax.swing.JCheckBox p22;
    private javax.swing.JCheckBox p23;
    private javax.swing.JCheckBox p24;
    private javax.swing.JCheckBox p3;
    private javax.swing.JCheckBox p4;
    private javax.swing.JCheckBox p5;
    private javax.swing.JCheckBox p6;
    private javax.swing.JCheckBox p7;
    private javax.swing.JCheckBox p8;
    private javax.swing.JCheckBox p9;
    // End of variables declaration//GEN-END:variables
}
