/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utilisateur;

import db.Donnees;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.Accueil;

/**
 *
 * @author Yannick MVOGO BEKONO
 */
public class profiles extends javax.swing.JFrame {

    /**
     * Creates new form listeProfiles
     */
    private Accueil parent;
    private boolean modal = true; 
    public profiles(Accueil parent) {
        initComponents();
        this.parent = parent;
        initTableau();
    }
    private void initTableau(){
        DefaultTableModel model = (DefaultTableModel) listeProfiles.getModel();
        model.setRowCount(0);
        for(int i = 0; i < Donnees.profiles.size(); i++){
            Profile p = Donnees.profiles.get(i);
            model.addRow(new Object[]{p.getNom(), p.getPrivileges()});
        }
    }
    @Override
    public void setVisible(boolean value) {
        this.initTableau();
        super.setVisible(value);
        if (value) {
          this.toFront();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeProfiles = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        p1 = new javax.swing.JCheckBox();
        p2 = new javax.swing.JCheckBox();
        p3 = new javax.swing.JCheckBox();
        p4 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        p5 = new javax.swing.JCheckBox();
        p6 = new javax.swing.JCheckBox();
        p7 = new javax.swing.JCheckBox();
        p8 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        p9 = new javax.swing.JCheckBox();
        p10 = new javax.swing.JCheckBox();
        p11 = new javax.swing.JCheckBox();
        p12 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        p13 = new javax.swing.JCheckBox();
        p14 = new javax.swing.JCheckBox();
        p15 = new javax.swing.JCheckBox();
        p16 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        p17 = new javax.swing.JCheckBox();
        p18 = new javax.swing.JCheckBox();
        p19 = new javax.swing.JCheckBox();
        p20 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        p21 = new javax.swing.JCheckBox();
        p22 = new javax.swing.JCheckBox();
        p23 = new javax.swing.JCheckBox();
        p24 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listeProfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Profiles", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeProfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeProfilesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeProfiles);
        if (listeProfiles.getColumnModel().getColumnCount() > 0) {
            listeProfiles.getColumnModel().getColumn(0).setResizable(false);
            listeProfiles.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Privileges"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Donnees des etudiants"));

        p1.setText("Afficher");
        p1.setEnabled(false);

        p2.setText("Creer");
        p2.setEnabled(false);
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        p3.setText("Modifier");
        p3.setEnabled(false);

        p4.setText("Supprimer");
        p4.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p1)
                .addGap(18, 18, 18)
                .addComponent(p2)
                .addGap(18, 18, 18)
                .addComponent(p3)
                .addGap(18, 18, 18)
                .addComponent(p4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p1)
                .addComponent(p2)
                .addComponent(p3)
                .addComponent(p4))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Donnees des enseignants"));

        p5.setText("Afficher");
        p5.setEnabled(false);

        p6.setText("Creer");
        p6.setEnabled(false);
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });

        p7.setText("Modifier");
        p7.setEnabled(false);

        p8.setText("Supprimer");
        p8.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p5)
                .addGap(18, 18, 18)
                .addComponent(p6)
                .addGap(18, 18, 18)
                .addComponent(p7)
                .addGap(18, 18, 18)
                .addComponent(p8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p5)
                .addComponent(p6)
                .addComponent(p7)
                .addComponent(p8))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Donnees des matieres"));

        p9.setText("Afficher");
        p9.setEnabled(false);

        p10.setText("Creer");
        p10.setEnabled(false);
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10ActionPerformed(evt);
            }
        });

        p11.setText("Modifier");
        p11.setEnabled(false);

        p12.setText("Supprimer");
        p12.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p9)
                .addGap(18, 18, 18)
                .addComponent(p10)
                .addGap(18, 18, 18)
                .addComponent(p11)
                .addGap(18, 18, 18)
                .addComponent(p12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p9)
                .addComponent(p10)
                .addComponent(p11)
                .addComponent(p12))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Notes des etudiants"));

        p13.setText("Afficher");
        p13.setEnabled(false);

        p14.setText("Creer");
        p14.setEnabled(false);
        p14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p14ActionPerformed(evt);
            }
        });

        p15.setText("Modifier");
        p15.setEnabled(false);

        p16.setText("Supprimer");
        p16.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p13)
                .addGap(18, 18, 18)
                .addComponent(p14)
                .addGap(18, 18, 18)
                .addComponent(p15)
                .addGap(18, 18, 18)
                .addComponent(p16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p13)
                .addComponent(p14)
                .addComponent(p15)
                .addComponent(p16))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Utilisateurs"));

        p17.setText("Afficher");
        p17.setEnabled(false);

        p18.setText("Creer");
        p18.setEnabled(false);
        p18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p18ActionPerformed(evt);
            }
        });

        p19.setText("Modifier");
        p19.setEnabled(false);

        p20.setText("Supprimer");
        p20.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p17)
                .addGap(18, 18, 18)
                .addComponent(p18)
                .addGap(18, 18, 18)
                .addComponent(p19)
                .addGap(18, 18, 18)
                .addComponent(p20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p17)
                .addComponent(p18)
                .addComponent(p19)
                .addComponent(p20))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Profiles"));

        p21.setText("Afficher");
        p21.setEnabled(false);

        p22.setText("Creer");
        p22.setEnabled(false);
        p22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p22ActionPerformed(evt);
            }
        });

        p23.setText("Modifier");
        p23.setEnabled(false);

        p24.setText("Supprimer");
        p24.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p21)
                .addGap(18, 18, 18)
                .addComponent(p22)
                .addGap(18, 18, 18)
                .addComponent(p23)
                .addGap(18, 18, 18)
                .addComponent(p24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p21)
                .addComponent(p22)
                .addComponent(p23)
                .addComponent(p24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Creer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Retour");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6ActionPerformed

    private void p10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p10ActionPerformed

    private void p14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p14ActionPerformed

    private void p18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p18ActionPerformed

    private void p22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p22ActionPerformed
    private boolean state(char c) {
        return c == '1';
    }
    private void initCheckBoxes(char[] privileges) {
        p1.setSelected(state(privileges[0]));
        p3.setSelected(state(privileges[2]));
        p4.setSelected(state(privileges[3]));
        p5.setSelected(state(privileges[4]));
        p6.setSelected(state(privileges[5]));
        p7.setSelected(state(privileges[6]));
        p8.setSelected(state(privileges[7]));
        p9.setSelected(state(privileges[8]));
        p10.setSelected(state(privileges[9]));
        p11.setSelected(state(privileges[10]));
        p12.setSelected(state(privileges[11]));
        p13.setSelected(state(privileges[12]));
        p14.setSelected(state(privileges[13]));
        p15.setSelected(state(privileges[14]));
        p16.setSelected(state(privileges[15]));
        p17.setSelected(state(privileges[16]));
        p18.setSelected(state(privileges[17]));
        p19.setSelected(state(privileges[18]));
        p20.setSelected(state(privileges[19]));
        p21.setSelected(state(privileges[20]));
        p22.setSelected(state(privileges[21]));
        p23.setSelected(state(privileges[22]));
        p24.setSelected(state(privileges[23]));
        p2.setSelected(state(privileges[1]));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(listeProfiles.getSelectedRowCount() == 1) {
            int l = listeProfiles.getSelectedRow();

            Profile u = new Profile(
                listeProfiles.getModel().getValueAt(l, 0).toString(),
                listeProfiles.getModel().getValueAt(l, 1).toString()
            );
            u.delete();
            initTableau();
        }
        else {
            JOptionPane.showMessageDialog(this, "Aucun profile n'a ete selectionne", "Selection non valide", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listeProfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeProfilesMouseClicked
        // TODO add your handling code here:
        if(listeProfiles.getSelectedRowCount() == 1) {
            Profile p = Donnees.profiles.get(listeProfiles.getSelectedRow());
            initCheckBoxes(p.getPrivileges());
        }
    }//GEN-LAST:event_listeProfilesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(listeProfiles.getSelectedRowCount() == 1) {
            Profile p = Donnees.profiles.get(listeProfiles.getSelectedRow());
            createP c = new createP(this, 1, p);
            c.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Aucun profile n'a ete selectionne", "Selection non valide", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        createP c = new createP(this, 2, null);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeProfiles;
    private javax.swing.JCheckBox p1;
    private javax.swing.JCheckBox p10;
    private javax.swing.JCheckBox p11;
    private javax.swing.JCheckBox p12;
    private javax.swing.JCheckBox p13;
    private javax.swing.JCheckBox p14;
    private javax.swing.JCheckBox p15;
    private javax.swing.JCheckBox p16;
    private javax.swing.JCheckBox p17;
    private javax.swing.JCheckBox p18;
    private javax.swing.JCheckBox p19;
    private javax.swing.JCheckBox p2;
    private javax.swing.JCheckBox p20;
    private javax.swing.JCheckBox p21;
    private javax.swing.JCheckBox p22;
    private javax.swing.JCheckBox p23;
    private javax.swing.JCheckBox p24;
    private javax.swing.JCheckBox p3;
    private javax.swing.JCheckBox p4;
    private javax.swing.JCheckBox p5;
    private javax.swing.JCheckBox p6;
    private javax.swing.JCheckBox p7;
    private javax.swing.JCheckBox p8;
    private javax.swing.JCheckBox p9;
    // End of variables declaration//GEN-END:variables
}
