/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package utilisateur;

import db.Donnees;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yannick MVOGO BEKONO
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    private int action;
    private Utilisateur utilisateur;
    private JFrame parent;
    public update(JFrame parent, Utilisateur u, int action) {
        this.action = action;
        this.parent = parent;
        initComponents();
        initComboBox();
        labelConfirmation.setVisible(false);
        cmdp.setVisible(false);
        if(action == 1) {
            utilisateur = u;
            nom.setText(u.getNom());
            mdp.setText(u.getMdp());
            profile.setSelectedItem(u.getProfile());
        }
        if(action == 2) {
            nom.setEnabled(true);
            nom.setEditable(true);
            mdp.setEnabled(true);
            mdp.setEditable(true);
            labelConfirmation.setVisible(true);
            cmdp.setVisible(true);
        }
    }
    private void initComboBox(){
        for(int i = 0; i < Donnees.profiles.size(); i++){
            profile.addItem(Donnees.profiles.get(i).getNom());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mdp = new javax.swing.JPasswordField();
        profile = new javax.swing.JComboBox<>();
        cmdp = new javax.swing.JPasswordField();
        labelConfirmation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Nom d'utilisateur");

        jLabel3.setText("Profile");

        jButton4.setText("Enregistrer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Annuler");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        nom.setEditable(false);
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        jLabel2.setText("Mot de passe");

        mdp.setEditable(false);

        labelConfirmation.setText("Confirmation du mot de passe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(labelConfirmation))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mdp)
                            .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdp)
                            .addComponent(profile, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfirmation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String p = profile.getSelectedItem().toString(),
            n = nom.getText(),
            m = Arrays.toString(mdp.getPassword()),
            cm = Arrays.toString(mdp.getPassword());
        if(action == 1){
            if(p.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informations manquantes", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else {
                utilisateur.setProfile(p);
                utilisateur.update();
            }
        }
        if(action == 2){
            if(p.isBlank() || n.isBlank() || cm.isBlank() || m.isBlank()) {
                JOptionPane.showMessageDialog(this, "Informations manquantes", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else {
                if(!m.equals(cm)) {
                    JOptionPane.showMessageDialog(this, "Les deux mots de passe ne correspondent pas", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
                else {
                    utilisateur = new Utilisateur(
                            n,
                            m,
                            p
                    );
                    if(utilisateur.create()){
                        JOptionPane.showMessageDialog(this, "Le nouvel utilisateur a bien ete cree et active.\nIl pourra modifier ses informations de connexion\n lors de sa prochaine session", "Nouvel utilisateur cree", JOptionPane.INFORMATION_MESSAGE);
                        parent.setVisible(true);
                        this.setVisible(false);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cmdp;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelConfirmation;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JTextField nom;
    private javax.swing.JComboBox<String> profile;
    // End of variables declaration//GEN-END:variables

}
