/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etudiant;

import db.Donnees;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.Accueil;
import note.bulletin;

/**
 *
 * @author Yannick MVOGO BEKONO
 */
public class liste extends javax.swing.JFrame {

    private Accueil parent;
    public liste(Accueil parent) {
        initComponents();
        this.parent = parent;
        initTableau();
    }
    @Override
    public void setVisible(boolean value) {
        this.initTableau();
        super.setVisible(value);
        if (value) {
          this.toFront();
        }
    }
    private void initTableau(){
        DefaultTableModel model = (DefaultTableModel) listeEtudiants.getModel();
        model.setRowCount(0);
        for(int i = 0; i < Donnees.etudiants.size(); i++){
            Etudiant e = Donnees.etudiants.get(i);
            model.addRow(new Object[]{e.getMatricule(), e.getNom(), e.getPrenom(), e.getId_classe(), e.getSexe(), e.getDate_naiss(), e.getQuartier()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeEtudiants = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        listeEtudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricule", "Nom", "Prenom", "Classe", "Sexe", "Date de nais.", "Quartier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listeEtudiants);
        if (listeEtudiants.getColumnModel().getColumnCount() > 0) {
            listeEtudiants.getColumnModel().getColumn(0).setResizable(false);
            listeEtudiants.getColumnModel().getColumn(3).setResizable(false);
            listeEtudiants.getColumnModel().getColumn(4).setResizable(false);
            listeEtudiants.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Gestion des etudiants");

        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Afficher les notes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ajouter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(listeEtudiants.getSelectedRowCount() == 1) {
            if(Donnees.profileUtilisateurConnecte.getPrivileges()[Donnees.SUPPRIMER_ETUDIANTS] == '1'){
                int l = listeEtudiants.getSelectedRow();
                Etudiant e = new Etudiant(
                        listeEtudiants.getModel().getValueAt(l, 0).toString(),
                        listeEtudiants.getModel().getValueAt(l, 1).toString(),
                        listeEtudiants.getModel().getValueAt(l, 2).toString(),
                        Integer.parseInt(listeEtudiants.getModel().getValueAt(l, 3).toString()),
                        listeEtudiants.getModel().getValueAt(l, 4).toString().charAt(0),
                        Date.valueOf(listeEtudiants.getModel().getValueAt(l, 5).toString()),
                        listeEtudiants.getModel().getValueAt(l, 6).toString()
                );
                e.delete();
            }
            else Donnees.actionInterdite(this);
        }
        else {
            JOptionPane.showMessageDialog(this, "Aucun etudiant n'a ete selectionne", "Selection non valide", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(listeEtudiants.getSelectedRowCount() == 1) {
            int l = listeEtudiants.getSelectedRow();
            
            Etudiant e = new Etudiant(
                    listeEtudiants.getModel().getValueAt(l, 0).toString(),
                    listeEtudiants.getModel().getValueAt(l, 1).toString(),
                    listeEtudiants.getModel().getValueAt(l, 2).toString(),
                    Integer.parseInt(listeEtudiants.getModel().getValueAt(l, 3).toString()),
                    listeEtudiants.getModel().getValueAt(l, 4).toString().charAt(0),
                    Date.valueOf(listeEtudiants.getModel().getValueAt(l, 5).toString()),
                    listeEtudiants.getModel().getValueAt(l, 6).toString()
            );
            Donnees.controlAction(this, Donnees.MODIFIER_ETUDIANTS, new update(this, 2, e));
        }
        else {
            JOptionPane.showMessageDialog(this, "Aucun etudiant n'a ete selectionne", "Selection non valide", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(listeEtudiants.getSelectedRowCount() == 1) {
            int l = listeEtudiants.getSelectedRow();
            
            Etudiant e = new Etudiant(
                    listeEtudiants.getModel().getValueAt(l, 0).toString(),
                    listeEtudiants.getModel().getValueAt(l, 1).toString(),
                    listeEtudiants.getModel().getValueAt(l, 2).toString(),
                    Integer.parseInt(listeEtudiants.getModel().getValueAt(l, 3).toString()),
                    listeEtudiants.getModel().getValueAt(l, 4).toString().charAt(0),
                    Date.valueOf(listeEtudiants.getModel().getValueAt(l, 5).toString()),
                    listeEtudiants.getModel().getValueAt(l, 6).toString()
            );
            Donnees.controlAction(this, Donnees.AFFICHER_NOTES, new bulletin(this, e));
        }
        else {
            JOptionPane.showMessageDialog(this, "Aucun etudiant n'a ete selectionne", "Selection non valide", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Donnees.controlAction(this, Donnees.CREER_ETUDIANTS, new update(this, 2,null));
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeEtudiants;
    // End of variables declaration//GEN-END:variables
}
